### ISSUE TITLE
PDF 417 Decoding in Flutter Web

### ISSUE THREAD

**Issue by BrayFlex** [shirne/zxing-dart#2]
Would you be able to make this work for Flutter Web, I've been trying to read PDF417 codes using a webcam and haven't had any luck with my own ports or using system channels with / js workarounds.

**Comment by shirne** [comment]
这个项目目前性能比java版差很多，我自己尝试的使用摄像头扫描时识别率也比较低。
The current performance of this project is much worse than that of the java version, and the recognition rate when I try to scan with the camera is also relatively low. 
我正在想办法做一些优化。
I am thinking of ways to do some optimizations. 
Web端扫描PDF417格式的我抽空测试一下是识别率问题还是Bug。
Scanning the PDF417 format on the web side, I took the time to test whether it is a recognition rate problem or a bug .

**Comment by JeffOlajos** [comment]
I've tried this code via Flutter Web and tried decoding a simple file that contains a QR code but that doesn't seem to work??? Any ideas or is this pkg simply not working yet?

**Comment by JeffOlajos** [comment]
if (img is ImageInfo)
      {
        ByteData data   = await img.image.toByteData(format: ImageByteFormat.rawRgba);
        bytes  = data.buffer.asUint8List();
        pixels = bytes.buffer.asInt32List();
        width  = img.image.width;
        height = img.image.height;
      }
      print ('image size (w,h) is (' + width.toString() + "," + height.toString() + ')');

     // bytes = Base64Codec().decode("iVBORw0KGgoAAAANSUhEUgAABLAAAASwCAQAAABBKHtEAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfkBQgJAzE5dzzdAAAeb0lEQVR42u3Zf5BeVX3H8e+aZ3eTkGwKsoAQhpZUgUUMDoTFjsTquKk6iKOotdHWJs4AjrW1LVKdNlSNOsowLbZVUzsYrRg61WhrtY7iz8WOJiguFYJUKTIGpGxIZPMDNiTZ/tXp3zufzJy9u6/X8/e5e865597nnTxVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjfXZgjqpLrIJnbevvt94BqfX+eEVvlFHo/Gr6uxo/OH6dufPwSW1ovEMvlVPNf37i+pFjXdgf30vvMLFdaJXWuf9oPbaBMZqxqfzn/Hm52hDvIahcAabw78/OQ+e5h3NT+Jw4x0Yar4DE/Eaxr3R5sFnTFw8zRYAAAgsAACBBQAgsAAAEFgAAAILAEBgAQAgsAAABBYAgMACAEBgAQAILAAAgQUAILAAABBYAAACCwBAYAEAILAAAAQWAIDAAgBAYAEACCwAAIEFAIDAAgAQWAAAAgsAQGABACCwAAAEFgCAwAIAQGABALTVswXHwRV1v00I3VRjC34PdtaxaPytdX40/ki8ghvq8mj8f9brGt+DL9V14RX2huOvqT+Mxh8KT0HVe+uVHX+Sbqu3eaWGVtUXbILAmgvur102IbTfFtQ58RVan8OVdV7HT8FU8z0cjvcwXcHj8+Bt4o3MHOAnQgAAgQUAILAAAAQWAAACCwBAYAEACCwAAAQWAIDAAgAQWAAACCwAAIEFACCwAAAEFgAAAgsAQGABAAgsAAAEFgCAwAIAEFgAAAgsAACBBQAgsAAAEFgAAAILAEBgAQAILAAABBYAgMACABBYAADMVs8WzAEjtbbjKzhQtyz4u/jj+vvwChur38MQ+lz9MBq/r65p/o/e7BwdjVdwjmNUb6hlHV/BeO1yGwUWVWvrox1fwUMCq75b3w2vsF5gxT4Y34NPN17Be8NAGqrHHYPYB+qMjq/gzQKrPT8RAgAILAAAgQUAILAAABBYAAACCwBAYAEAILAAAAQWAIDAAgBAYAEACCwAAIEFACCwAAAQWAAAAgsAQGABACCwAAAEFgCAwAIAQGABAAgsAACBBQCAwAIAEFgAAAILAEBgAQAgsAAABBYAgMACAEBgAQA01rMFUFVVO2t1NP6TdVU4g5OrLxp/pPP3YE1NN57BP9fi8Aq76+SmK5iKV5A65mUCAgv+30ANROP74xkcXvD3oC+8B7lFzRMvN+1hhrnAT4QAAAILAEBgAQAILAAABBYAgMACABBYAAAILAAAgQUAILAAABBYAAACCwBAYAEACCwAAAQWAIDAAgAQWAAACCwAAIEFACCwAAAQWAAAAgsAQGABACCwAAAEFgCAwAIAEFgAAAgsAACBBQAgsAAAmK2eLYCqqvrrOjUa/6PmK1hXL47GH6j3dP4u/l39PBo/WDeEM7ixZqLxS8IZPFnXe5hBYMHc8cnOr+Cyens0fs88CKxbakc0fn19OpzBKTUZjd8U3sX9AgvmBj8RAgAILAAAgQUAILAAABBYAAACCwBAYAEAILAAAAQWAIDAAgBAYAEACCwAAIEFACCwAAAQWAAAAgsAQGABACCwAAAEFgCAwAIAQGABAAgsAACBBQCAwAIAEFgAAAILAEBgAQAgsAAABBYAgMACAGC2erZgDjhQD3V8Bb+YB3fhlBpoPIOHaiYa/3h4jvbVynAFT4QzGKjhzp+jZ9RgNH7IC9Eb7bh8qyCwqKpb6hab0NxXa3XjGayoqWj8jXVjNH64Hg1X8Pp6UzR+tL7X+XN0l0dpHlhjC8j5iRAAQGABAAgsAACBBQCAwAIAEFgAAAILAACBBQAgsAAABBYAAAILAEBgAQAILAAAgQUAgMACABBYAAACCwAAgQUAILAAAAQWAAACCwBAYAEACCwAAAQWAIDAAgAQWAAAAgsAAIEFACCwAAAEFgAAAgsAoLGeLTgObqr9NiF0aedX8M36cHiFj1V/NP7W+qyD1NzGmorGv7pe13gFb6kXReMfqGubv022O4ih5bZAYM0NY7aAejB+qW8NX2oTbsIc8MWajMaPNF/BxfWqaPxdzVdwergCOC78RAgAILAAAAQWAIDAAgBAYAEACCwAAIEFAIDAAgAQWAAAAgsAAIEFACCwAAAEFgCAwAIAQGABAAgsAACBBQCAwAIAEFgAAAILAACBBQAgsAAABBYAAAILAEBgAQAILAAAgQUAgMACABBYAAACCwCA2erZgtpXt9uEzrur+QxOrbXhFb5Xi6PxDzbfg3PDPTgvnsGFNRiNPyl+G1xUh6LxfeEMnozP4ameZo7LNytAVVVN1Ezjz1DjHRhuvgPtP9viXZwMZ7A5/PtDzfdwwssEqvxECAAgsAAABBYAgMACAEBgAQAILAAAgQUAgMACABBYAAACCwAAgQUAILAAAAQWAIDAAgBAYAEACCwAAIEFAIDAAgAQWAAAAgsAAIEFACCwAAAEFgAAAgsAQGABAAgsAACBBQCAwAIAEFgAAAILAACBBQDQXM8WHAfba1XjGayppzq+hzfWi6PxP6g3hTP47VoSjb+i3h3O4Dt1LBr/4fqHaPzeem64gvfXSxufo9+tu6Pxl9ZEOIMTG+/AgfguvruuaLyGm+uixjNYV49G499YfxyNP1yX+GIVWFRVnVfnNZ5B9/8n8tdqdTR+Kp7BfeH458YzuCAcf1o4/mgcF79sfo5+Eq5hJDyH7R2L7+Le5mt4ZvO7MBCOPzVcwWFfq/OBnwgBAAQWAIDAAgAQWAAACCwAAIEFACCwAAAQWAAAAgsAQGABACCwAAAEFgCAwAIAEFgAAAgsAACBBQAgsAAAEFgAAAILAEBgAQAgsAAABBYAgMACAEBgAQAILAAAgQUAILAAABBYAAACCwBAYAEAMFs9W0BVXVwXNJ7B/fWJaPx98QyuqKdH45/f+VMwWOvDK/w8vIsn1+UdP4dVv1ODXig097w6t/EMvlIPCyyoem29vfEMXl3bG8/gPbV6gZ+Cofp4eIXX17Zo/GjzwNpRO8IrXC6wmAPeWFc3nsE6geUnQgAAgQUAILAAAAQWAAACCwBAYAEACCwAAAQWAIDAAgAQWAAACCwAAIEFACCwAAAEFgAAAgsAQGABAAgsAAAEFgCAwAIAEFgAAAgsAACBBQAgsAAAEFgAAAILAEBgAQAILAAABBYAgMACABBYAAAILACAxnq24DhYU4saz2B3DUbj31crGq/gY7U1Gv8f9VIHMbQnPgWHwvHfj2dwMBz/mro5vMJzam80ftpBrJeE30xX1Kcar+Cm2hKNH6ipcAbvCJ+lc2qngyiw5oKDzWcwVAPR+Jn4cU711/Jo/AmOYaz9KTja+XNYdbD5GrovDfUnmq/gcB2Oxg/G5/BYeA4POoY5PxECAAgsAACBBQAgsAAAEFgAAAILAEBgAQAgsAAABBYAgMACAEBgAQAILAAAgQUAILAAABBYAAACCwBAYAEAILAAAAQWAIDAAgBAYAEACCwAAIEFAIDAAgAQWAAAAgsAQGABACCwAAAEFgCAwAIAYLZ6tqBW1e+HV/ibmmy8hneFd/L25nfh1pqIxvfV5nAGp4Xjf1ifD6/w5zXocQxdVWdG44/W9eEMDjbegcH6i/AKz42fpM2N9+Dc+ArX1v6mK5iJz+HOcPyj8Qx+6nVE1VjNhJ8Rm9jc2vgupp+t8RqmwhlscgxqR7iH2zq/A0PNnwSf/DPtUZ4P/EQIACCwAAAEFgCAwAIAQGABAAgsAACBBQCAwAIAEFgAAAILAACBBQAgsAAABBYAgMACAEBgAQAILAAAgQUAgMACABBYAAACCwAAgQUAILAAAAQWAAACCwBAYAEACCwAAIEFAIDAAgAQWAAAAgsAgNnq2YLj4MQatgmNLa098V1cFI0fjE9Bn9sY2xeeg+n4Lu6pmaY7cCx+EpbX4II/R3vrWDR+SZ3QeAXLakk0/kjt8zohN1YzPp3/jMfnYKLze7DJwxxbH9+F7v9ja6v3Sa0M9/C68O9Px3dxSziDXV4GOT8RAgAILAAAgQUAILAAABBYAAACCwBAYAEAILAAAAQWAIDAAgBAYAEACCwAAIEFACCwAAAQWAAAAgsAQGABACCwAAAEFgCAwAIAQGABAAgsAACBBQCAwAIAEFgAAAILAEBgAQAgsAAABBYAgMACAEBgAQA01rMFc8DX6+PhFT7Z+Tt5U90RjT+ptoUz2FJT0fi1dbWjHFpVm8MrbKr7O74Hr6zXNJ7BRL2+8Qw21bnR+DvqpnAGj3X+Wbq5xqPxy+I36vvrbq80xmqm8WdLvIbp5mtIP1eGO7A2nsGF4Qw2NN/DTZ1/FkfjPRgNZ7A+nsFwHBetz9GG5udgPFzB9uYruC5cwXTzFYzE52hMXPiJEABAYAEACCwAAIEFAIDAAgAQWAAAAgsAAIEFACCwAAAEFgAAAgsAQGABAAgsAACBBQCAwAIAEFgAAAILAACBBQAgsAAABBYAAAILAEBgAQAILAAABBYAgMACABBYAAACCwAAgQUAILAAAAQWAACz1bMF9XjtbDyDB+Ir7KyBjt+Fp9doNH5lfBcPhuMnm5+jh5rfxVV1cjT+rHgPD4Tj98QzuCA8SSub38Wzw2fxYN0dzmBXDYZ3cTScwQ/rcNN70Bev4IF61Jc7UFW1vWaiz7gtnAO2hXdxxzzYg8lwD7r/mWh+D66M15Bm7nXN78I14QpG4hmMeSH6iRAAQGABAAgsAACBBQCAwAIAEFgAAAILAACBBQAgsAAABBYAAAILAEBgAQAILAAAgQUAgMACABBYAAACCwAAgQUAILAAAAQWAAACCwBAYAEACCwAAAQWAIDAAgAQWAAAAgsAAIEFACCwAAAEFgAAAgsAoLGeLZgXbq+Bjq/g5rohGj8Vz+BT9azGe/DCOhSNv6reFI3fVy9pvAPn147wChvrnsZr+K3qD1dwVcef5WfGdzE1UZfG76NficY/I/z7T9Vl4RUeiMene3ivL2aBNT9c0vnAuqH5S/mCWt3xp/HMuiQav6f5KTghXEHVsuZruDMcv67zb6Ol8V1M7Y7fJufXGU1XMNP8ffhE8xnMA34iBAAQWAAAAgsAQGABACCwAAAEFgCAwAIAQGABAAgsAACBBQCAwAIAEFgAAAILAEBgAQAgsAAABBYAgMACAEBgAQAILAAAgQUAgMACABBYAAACCwAAgQUAILAAAAQWAIDAAgBAYAEACCwAAIEFAMBs9WxBnVYvajyDn9Qd4RX+qfo7fhfOqvXR+Efra+EM/r12RePPrlEPU3PralXHV/CccPyR+kx4hdE6Oxr/y/pyOIMX13A0/szwbVL1lVrS9BQ8FV9hTT2z8Un+Rj3ihcRYzTT+bHETanu4h+PNV7AhPgdD4Qw2h39/Mt6Dbc2fJZ+p+C5uDWcwEc9gvPkuruz8G3VL8z0c87XmJ0IAAIEFACCwAAAEFgAAAgsAQGABAAgsAAAEFgCAwAIAEFgAAAgsAACBBQAgsAAABBYAAAILAEBgAQAILAAABBYAgMACABBYAAAILAAAgQUAILAAABBYAAACCwBAYAEACCwAAAQWAIDAAgAQWAAACCwAgMb6bEGN1VfDKzy//isa/9p6VziDM+pwNP76ems0/uFaHa5gqAaj8RfVp8IZvLDujsYP1lA4g521LBq/tJZG42fqsXAFy8O7eGe9pPHb4FW1JbzCeeEu/km9Ixq/Pz6Hy2txNP7c+lw4gxXVH43/Ym0MZ/BYHYvG/0H9ZTR+ulaGK1hWS6Lxz6rvhDNYV7ct9Ljo6avjYF9NRuOP1smNQ3lZOIPpeA+nwvGH4j1Mn4Xp8BRUPb2WN/7n1smNn6Qj8R6m9sdXeCxcw6Hm77P94S6c0fwcHW5+jpaGe3A4nsGBOhCNH/bFnvMTIQCAwAIAEFgAAAILAACBBQAgsAAABBYAAAILAEBgAQAILAAABBYAgMACABBYAAACCwAAgQUAILAAAAQWAAACCwBAYAEACCwAAAQWAIDAAgAQWAAACCwAAIEFACCwAAAEFgAAAgsAQGABAAgsAABmq2cL6r/rveEVJpuv4Z11NBr/vPDvL69NjXegL76LV9TLG6/hpuqLxr+gLuv4s3h6fI5uroc7vgfj4UmeiffwC3VXNP6R+FlM3RNf4Y9qKBr//PDvL4rv4pfqTl/uUHVNzfiEn/H4Lkw0X8NQuILNzkGNhnu4Pp7BcOO3yVC8gg1eybW780/CNeEOjMQzGHOM/EQIACCwAAAEFgCAwAIAQGABAAgsAACBBQCAwAIAEFgAAAILAACBBQAgsAAABBYAgMACAEBgAQAILAAAgQUAgMACABBYAAACCwAAgQUAILAAAAQWAAACCwBAYAEACCwAAIEFAIDAAgAQWAAAAgsAgNnq2YJaVCc0nsHi+Ar7G6+gr5aFV3iijkTjn6yheAbZLvbH93F5OH6g+bOU3sVFtTScwdLwHCxpvocD4TlaHs9gcfwstfZUPRG/UfeHd3Gw8Tv9afGTkM7gSEGN1UznP4ON93BlvIIrwxmsjWdwYTiDDfPgHKWf9eEejs6DPRgO92CTcxR/tjf/VrkuXMF0PIMt4Qx2SYOcnwgBAAQWAIDAAgAQWAAACCwAAIEFACCwAAAQWAAAAgsAQGABACCwAAAEFgCAwAIAEFgAAAgsAACBBQAgsAAAEFgAAAILAEBgAQAgsAAABBYAgMACAEBgAQAILAAAgQUAILAAABBYAAACCwBAYAEAILAAABrr2YK6pzY2nsFv1u81nsFr6mXR+KXxDN5Sl0fjT41n8O7aG41/JD5HH6nF0fjP179F45fXh8IVXF1j0fip5s/iaF3deAZfqN3R+MX1kQX/Tr+otjaewbN9scLccE3NhJ/BcAY3xDPwyV/pU+EMNoV/f7j5Hu5o/iyuj9cw3HgFQ57FefCZjs/BlnAGu3wx5/xECAAgsAAABBYAgMACAEBgAQAILAAAgQUAgMACABBYAAACCwAAgQUAILAAAAQWAIDAAgBAYAEACCwAAIEFAIDAAgAQWAAAAgsAAIEFACCwAAAEFgAAAgsAQGABAAgsAACBBQCAwAIAEFgAAAILAIDZ6tmCOWBP3RVe4Vg4/uF4Bt13Ti2Oxp9UF4YzuKeWROMfCf/+keanYHe8h6mz4is8u/aFdzG7j0fju3hmnRSNf7Lu6/zbYKT6F/j7cDB+Fn9aB3y5A1VVEzXT+DO04O/BaPN70P6zufld2BquYGIenMTdjU/BdLyCLc1P8pgvFT8RAgAILAAAgQUAILAAABBYAAACCwBAYAEAILAAAAQWAIDAAgBAYAEACCwAAIEFACCwAAAQWAAAAgsAQGABACCwAAAEFgCAwAIAQGABAAgsAACBBQCAwAIAEFgAAAILAEBgAQAgsAAABBYAgMACAEBgAQA01rMFdXH9lU3ovLvqreEVNtayxmv4bC1e4HdxefMZfK02N57Bgx7m+ttaHY3/dm3q+A7013h4hX+tF0Tjz6p/dBAFVu7EuswmUHc2n8GlcyAwFrrJ+IuN3OrwnTzZ+R3oi7+VtoUnecQxzPmJEABAYAEACCwAAIEFAIDAAgAQWAAAAgsAAIEFACCwAAAEFgAAAgsAQGABAAgsAACBBQCAwAIAEFgAAAILAACBBQAgsAAABBYAAAILAEBgAQAILAAABBYAgMACABBYAAACCwAAgQUAILAAAAQWAACz1bMFx8Fttd8mhC6t0zu+grPq4sZP4676ceM9WFNnRuP31TfDGbywTmy8B5fXYDT+3toVnqJXxCe5tW/XZDT+u51/Hx6rfwmvsKKujMYP1efCGfyPrzWqxmom/IzYxNj28B6MN1/BhvgcpZ9NzfdgW7iCHfEMdoQz2BbPYDKcwebw7w81P4cT8+B9tLvxHk7HK9gSzmCXL6WcnwgBAAQWAIDAAgAQWAAACCwAAIEFACCwAAAQWAAAAgsAQGABACCwAAAEFgCAwAIAEFgAAAgsAACBBQAgsAAAEFgAAAILAEBgAQAgsAAABBYAgMACAEBgAQAILAAAgQUAILAAABBYAAACCwBAYAEAILAAABrr2YI54A31gY6v4Be1xm1s7tq6Ohr/WK1uvIILa3d4hY21Kxp/yDGKjcR3sb3TwvEfrfdH42ccI4HF8bGszrAJxIZqKBo/2HwFA/GT8Pg8+HLvun7vszrgHOInQgAAgQUAILAAAAQWAAACCwBAYAEACCwAAAQWAIDAAgAQWAAACCwAAIEFACCwAAAEFgAAAgsAQGABAAgsAAAEFgCAwAIAEFgAAAgsAACBBQAgsAAAEFgAAAILAEBgAQAILAAABBYAgMACABBYAADMXs8WwBzxoTrc9O8fcAuoqi/X3dH4U+qN4Qxurd3R+GfVKzp+DxbVn4ZXWO0gCyzg/1xfUzaB5j5TW6PxF8aBtaXGo/FXdj6wevVBB7H7/EQIACCwAAAEFgCAwAIAQGABAAgsAACBBQCAwAIAEFgAAAILAACBBQAgsAAABBYAgMACAEBgAQAILAAAgQUAgMACABBYAAACCwAAgQUAILAAAAQWAAACCwBAYAEACCwAAIEFAIDAAgAQWAAAAgsAgNnq2QKoqqr+8J8bfXU4nMFM8z0Y7Pw/2PrDNRytI41XsChcwUB8DvvCGfR7mcwDffHb4PAceKMJLJgT7qjV0fhPxC+k1obr0c7fxdvD8bfW+sYreGe9Mxq/Pz6HW+tmr4MF79x6MrzCurptoW+inwgBAAQWAIDAAgAQWAAACCwAAIEFACCwAAAQWAAAAgsAQGABACCwAAAEFgCAwAIAEFgAAAgsAACBBQAgsAAAEFgAAAILAEBgAQAgsAAABBYAgMACAEBgAQAILAAAgQUAILAAABBYAAACCwBAYAEAILAAABrr2YI5YLze3PEVHHAT63m1JbzC2+rJju/Bx+uOaPyv1p+FM/hg/Swa/5N4D66tJdH4l9XLO34Kdtf7wiukd+HO5m/UU8K3wbHOfydU3etLgaqxmgk/IzYxtj28B+PxDCbic5B+hhrfg+F4BevDGYzGMxjt/JOwKdyBqXgGW8MZTHid1XXhHk7bwvnAT4QAAAILAEBgAQAILAAABBYAgMACABBYAAAILAAAgQUAILAAABBYAAACCwBAYAEACCwAAAQWAIDAAgAQWAAACCwAAIEFACCwAAAQWAAAAgsAQGABACCwAAAEFgCAwAIAEFgAAAgsAACBBQAgsAAAmK2eLTgOVtmC2PLmM7i/BqLxK+r0cAbn1MGmO3Bi83twqO4Nr3BqjTRew311NBo/Ge7BgeZ3cTC+Bz+rQ+Hb5MzGe3BK59/IA/Xr4RUebPw+Y04Yqxmfzn/Gm5+jDe5CrW9+F3Y034Phzr8Rtzbfw7XhCq7s/JM03fwUjMRrGBMXfiIEABBYAAACCwBAYAEAILAAAAQWAIDAAgBAYAEACCwAAIEFAIDAAgAQWAAAAgsAQGABACCwAAAEFgCAwAIAQGABAAgsAACBBQCAwAIAEFgAAAILAACBBQAgsAAABBYAgMACAEBgAQAILAAAgQUAgMACAGiszxbUSXWRTei8ffX9xjM4vc5f8HfhR/VI4xlcUisaz+Bb9VTH7+JIndF4BnfUL6Pxp9Tqjt+DY/X1xjM4oX4jvMIPaq8vJgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgMb+Fwu38BZAZoGIAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIwLTA1LTA4VDA5OjAzOjQ5KzAwOjAwPHWOxQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMC0wNS0wOFQwOTowMzo0OSswMDowME0oNnkAAAAASUVORK5CYII=");

      LuminanceSource source = RGBLuminanceSource(width, height, pixels);
      var bitmap = BinaryBitmap(HybridBinarizer(source));

**Comment by shirne** [comment]
The RGBLuminanceSource needs a pixels param one element per pixel.
The rawRgba data is a Uint8List store a pixel in 4 elements by alpha, red, green, blue.
You can translate it like
```dart
int byte2Pixel(Uint8List byteData, int firstIndex){
    return byteData[firstIndex + 3] << 24 + byteData[firstIndex] << 16  + byteData[firstIndex+1] << 8 + byteData[firstIndex+2] ;
}
```

**Comment by JeffOlajos** [comment]
Thanks.  I’ll give that a try.  I wasn’t even able to decide the same file with your demo program.

**Comment by JeffOlajos** [comment]
Good work here. This will garner a lot of attention if done right. Are you planning on adding the code_39 _extended?

**Comment by shirne** [comment]
> Great work btw. This will garner a lot of attention if done right. Are you planning on adding the code_39 _extended?

In fact, I don't know much about the types of barcodes. The codes here is completely translated according to the zxing-java version.
What is the difference between code_39_extended and code_39? Is there any documentation on this? If it is not too much trouble, you can try it, but I am not sure yet.

**Comment by shirne** [comment]
> Thanks. I’ll give that a try. I wasn’t even able to decode the same image file with your demo program. Our real challenge is pdf417

Regarding the pdf417 format, the Case in the test project has passed, but the decoding rate in actual use is relatively low, especially for the scanning of screen devices. I currently have no better way of this. Maybe some processing (such as homogenization or moiré removal) on the picture before decoding will have better results, but I am not good at this aspect.

**Comment by shirne** [comment]
@BrayFlex 
> Would you be able to make this work for Flutter Web, I've been trying to read PDF417 codes using a webcam and haven't had any luck with my own ports or using system channels with / js workarounds.

我尝试了下web端编码和解码工作，采用web接口调用摄像头的方案一直有问题，没有太好的解决办法。可以使用选择文件中的照相操作代替。
I tried the web-side encoding and decoding work. The solution of using the web interface to call the camera has always been problematic, and there is no good solution. You can use the camera operation in the selected file instead.
具体效果可以查看这个项目。这个issue我就先关掉了。
The specific effect can be viewed in this project. I will close this issue first. 
https://github.com/shirne/zxingweb
