### ISSUE TITLE
iOS YUV420无法正常解析二维码

### ISSUE THREAD

**Issue by v7lin** [shirne/zxing-dart#3]
如题，Android的YUV420能正常解析二维码，而iOS的YUV420不行

**Comment by shirne** [comment]
有演示代码吗？

**Comment by shirne** [comment]
是图片解码还是拍照解码？图片的话结果应该是一致的，拍照的可能不同设备会有差别

**Comment by v7lin** [comment]
我查了一些资料，发现iOS的YUV 420和Android的YUV420不是一个东西，iOS智能改成BGRA8888了
