### ISSUE TITLE
How to use with ImageStream

### ISSUE THREAD

**Issue by thewh1teagle** [shirne/zxing-dart#4]
In camera module we have an option to get stream of frames
`_controller.startImageStream( CameraImgae image => { } )`
How can I decode it from that CameraImage object?
In your example you decode it from Xpic file, but I prefer to decode it with stream because it should be more efficient for live decode

In addition, when I get the results, does it possible to get the positions of each result? like we can in `flutter_zxing` lib.

**Comment by shirne** [comment]
1.  I add a demo page that decode from CameraImage(yuv data) only test on android e953866decef048a8e8344263d6122192a7ba2e0
 2. Each result has a resultPoints
> return points related to the barcode in the image. These are typically points   identifying finder patterns or the corners of the barcode. The exact meaning is  specific to the type of barcode that was decoded.

**Comment by thewh1teagle** [comment]
Thank you very much for the example. 
I tried it on my machine, 
it looks like it takes more than 400ms to decode image.
and that's strange because the original zxing library of flutter takes less than 1ms
My goal is to create animation on the positions of detected qr's in live,
is there a way to reduce the time it takes?

**Comment by shirne** [comment]
Currently , it's hard.
If you are only use for stadard qrcode , you can set single decoder mode and close  inverse mode.

Or I recommand  you to use  [mk_kit ](https://developers.google.cn/ml-kit/vision/barcode-scanning), there's also some plugin on pub.

**Comment by shirne** [comment]
@thewh1teagle 
I improved CameraImage decode fundation to use a persistent isolate.
And thanks for your remind, decode CameraImage is more faster then a capture image.

**Comment by thewh1teagle** [comment]
Is it significantly faster? if not, what makes it hard to make it fast as zxing?
