### ISSUE TITLE
Some files are missing in pub.dev package repository

### ISSUE THREAD

**Issue by narian** [shirne/zxing-dart#6]
**Describe the bug**
Package installed through flutter pub add does not have same amount of files that git repo has. 

**To Reproduce**
1. Create a project
2. Add package through `flutter pub add zxing_lib` command
3. Copy decoder.dart from examples
4. `lib/models/decoder.dart:188:17: Error: Couldn't find constructor 'DecodeHint'.` in the debug console

Tried reinstalling and updating package, no effect.

**Expected behavior**
No errors 

**Screenshots**
Attached screenshot with missing decode_hint.dart (and others) file 

![List of file from flutter pub](https://github.com/shirne/zxing-dart/assets/879212/8ce90920-b0a9-4368-8644-fd5ace3d3294)

**Comment by shirne** [comment]
This class is a feature in 1.0.0.
before 1.0.0, use Map<DecodeHintType, dynamic> for decode hint
